export const config = {
  MAX_HAND_SIZE: 6,
  MAX_MANA: 9,
  CARD_DRAW_PER_TURN: 2,
  MAX_REPLACES_PER_TURN: 1,
  PLAYER_1_STARTING_MANA: 2,
  PLAYER_2_STARTING_MANA: 3,
  STARTING_HAND: 3,
  UNIT_REACH: 2,
  GENERAL_DEFAULT_ATTACK: 2,
  GENERAL_DEFAULT_HP: 25
} as const;
